<?php
$cr_result_checker = "CREATE TABLE IF NOT EXISTS `result_checker` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `fullname` varchar(225) NOT NULL,
    `adm_no` varchar(225) NOT NULL,
    `term` varchar(255) NOT NULL,
    `session` varchar(225) NOT NULL,
    `code` varchar(225) NOT NULL,
    `validity` varchar(225) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;";

mysqli_query($conn, $cr_result_checker);


$cr_evaluation = "CREATE TABLE IF NOT EXISTS `evaluation` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `fullname` varchar(225) NOT NULL,
    `term` varchar(225) NOT NULL,
    `session` varchar(225) NOT NULL,
    `adm_no` varchar(225) NOT NULL,
    `overall_score` int(11) NOT NULL,
    `out_of` int(11) NOT NULL,
    `percent_score` float(11) NOT NULL,
    `t_comment` varchar(500) NOT NULL,
    `p_comment` varchar(500) NOT NULL,
    `n_absent` int(11) NOT NULL,
    `n_present` int(11) NOT NULL,
    `punctuality` int(11) NOT NULL,
    `attentiveness` int(11) NOT NULL,
    `neatness` int(11) NOT NULL,
    `honesty` int(11) NOT NULL,
    `relationship` int(11) NOT NULL,
    `skills` int(11) NOT NULL,
    `sport` int(11) NOT NULL,
    `clubs` int(11) NOT NULL,
    `fluency` int(11) NOT NULL,
    `handwriting` int(11) NOT NULL,
    `position` varchar(255) NOT NULL,
    `promoted_to` varchar(225) NOT NULL,
    `next_term_date` varchar(225) NOT NULL,
    `class` varchar(225) NOT NULL,
    `status` varchar(225) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;";

mysqli_query($conn, $cr_evaluation);

$cr_admin_table = $conn->query("CREATE TABLE IF NOT EXISTS `admin_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `surname` varchar(255) NOT NULL,
  `gender` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `assignedClass` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `position` varchar(255) NOT NULL,
  `signature` varchar(255) NOT NULL,
  `reset` int(11) NOT NULL,
  `keyp` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");


if ($cr_admin_table) {
  $check = $conn->query("SELECT * FROM $admin_tbl WHERE username = 'Admin'");
  if ($check->num_rows == 0) {
    $conn->query("INSERT INTO $admin_tbl (name, surname, gender, email, username, password, token, position) 
    VALUES('School', 'management', 'gender', 'school@example.com', 'Admin', 'bdb52d04dc20036dbd8313ed055', '3b4439366d25394e2f391e52ed10fa5f', 'Proprietor')");
  }
}

$cr_class_tbl = $conn->query("CREATE TABLE IF NOT EXISTS `class_tbl` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `class` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

if ($cr_class_tbl) {
  $checkCl = $conn->query("SELECT * FROM $class_tbl WHERE class = 'JSS-1'");
  if ($checkCl->num_rows == 0) {
    $conn->query("INSERT INTO $class_tbl (class) VALUE('JSS-1')");
  }
}
$cr_e_ctrl = $conn->query("CREATE TABLE IF NOT EXISTS `exam_controller` (
  `c_id` int(11) NOT NULL AUTO_INCREMENT,
  `day` varchar(255) NOT NULL,
  `exam_order` varchar(255) NOT NULL,
  `term` varchar(255) NOT NULL,
  PRIMARY KEY (`c_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

if ($cr_e_ctrl) {
  $checkCtrl = $conn->query("SELECT * FROM $exam_crtl_tbl WHERE day != ''");
  if ($checkCtrl->num_rows == 0) {
    $conn->query("INSERT INTO $exam_crtl_tbl (day) VALUE('null')");
  }
}
$cr_ft_answer_sheet = $conn->query("CREATE TABLE IF NOT EXISTS `ft_answer_sheet` (
  `A_id` int(11) NOT NULL AUTO_INCREMENT,
  `subject` mediumtext NOT NULL,
  `paper_type` text NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `teacher` varchar(255) NOT NULL,
  `teacher_token` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `duration` int(11) NOT NULL,
  `session` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `fullname` varchar(255) NOT NULL,
  `adm_no` varchar(255) NOT NULL,
  `CA1` int(11) NOT NULL,
  `CA2` int(11) NOT NULL,
  `CA3` int(11) NOT NULL,
  `test` int(11) NOT NULL,
  `obj_score` int(11) NOT NULL,
  `essay_score` int(11) NOT NULL,
  `exam_total` int(11) NOT NULL,
  `total` int(11) NOT NULL,
  `position` varchar(255) NOT NULL,
  `grade` text NOT NULL,
  `remark` varchar(255) NOT NULL,
  `color` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `Q1` int(255) NOT NULL,
  `Qid1` text NOT NULL,
  `Q2` int(255) NOT NULL,
  `Qid2` text NOT NULL,
  `Q3` int(255) NOT NULL,
  `Qid3` text NOT NULL,
  `Q4` int(255) NOT NULL,
  `Qid4` text NOT NULL,
  `Q5` int(255) NOT NULL,
  `Qid5` text NOT NULL,
  `Q6` int(255) NOT NULL,
  `Qid6` text NOT NULL,
  `Q7` int(255) NOT NULL,
  `Qid7` text NOT NULL,
  `Q8` int(255) NOT NULL,
  `Qid8` text NOT NULL,
  `Q9` int(255) NOT NULL,
  `Qid9` text NOT NULL,
  `Q10` int(255) NOT NULL,
  `Qid10` text NOT NULL,
  `Q11` int(255) NOT NULL,
  `Qid11` text NOT NULL,
  `Q12` int(255) NOT NULL,
  `Qid12` text NOT NULL,
  `Q13` int(255) NOT NULL,
  `Qid13` text NOT NULL,
  `Q14` int(255) NOT NULL,
  `Qid14` text NOT NULL,
  `Q15` int(255) NOT NULL,
  `Qid15` text NOT NULL,
  `Q16` int(255) NOT NULL,
  `Qid16` text NOT NULL,
  `Q17` int(255) NOT NULL,
  `Qid17` text NOT NULL,
  `Q18` int(255) NOT NULL,
  `Qid18` text NOT NULL,
  `Q19` int(255) NOT NULL,
  `Qid19` text NOT NULL,
  `Q20` int(255) NOT NULL,
  `Qid20` text NOT NULL,
  `Q21` int(255) NOT NULL,
  `Qid21` text NOT NULL,
  `Q22` int(255) NOT NULL,
  `Qid22` text NOT NULL,
  `Q23` int(255) NOT NULL,
  `Qid23` text NOT NULL,
  `Q24` int(255) NOT NULL,
  `Qid24` text NOT NULL,
  `Q25` int(255) NOT NULL,
  `Qid25` text NOT NULL,
  `Q26` int(255) NOT NULL,
  `Qid26` text NOT NULL,
  `Q27` int(255) NOT NULL,
  `Qid27` text NOT NULL,
  `Q28` int(255) NOT NULL,
  `Qid28` text NOT NULL,
  `Q29` int(255) NOT NULL,
  `Qid29` text NOT NULL,
  `Q30` int(255) NOT NULL,
  `Qid30` text NOT NULL,
  `Q31` int(255) NOT NULL,
  `Qid31` text NOT NULL,
  `Q32` int(255) NOT NULL,
  `Qid32` text NOT NULL,
  `Q33` int(255) NOT NULL,
  `Qid33` text NOT NULL,
  `Q34` int(255) NOT NULL,
  `Qid34` text NOT NULL,
  `Q35` int(255) NOT NULL,
  `Qid35` text NOT NULL,
  `Q36` int(255) NOT NULL,
  `Qid36` text NOT NULL,
  `Q37` int(255) NOT NULL,
  `Qid37` text NOT NULL,
  `Q38` int(255) NOT NULL,
  `Qid38` text NOT NULL,
  `Q39` int(255) NOT NULL,
  `Qid39` text NOT NULL,
  `Q40` int(255) NOT NULL,
  `Qid40` text NOT NULL,
  `Q41` int(255) NOT NULL,
  `Qid41` text NOT NULL,
  `Q42` int(255) NOT NULL,
  `Qid42` text NOT NULL,
  `Q43` int(255) NOT NULL,
  `Qid43` text NOT NULL,
  `Q44` int(255) NOT NULL,
  `Qid44` text NOT NULL,
  `Q45` int(255) NOT NULL,
  `Qid45` text NOT NULL,
  `Q46` int(255) NOT NULL,
  `Qid46` text NOT NULL,
  `Q47` int(255) NOT NULL,
  `Qid47` text NOT NULL,
  `Q48` int(255) NOT NULL,
  `Qid48` text NOT NULL,
  `Q49` int(255) NOT NULL,
  `Qid49` text NOT NULL,
  `Q50` int(255) NOT NULL,
  `Qid50` text NOT NULL,
  `Q51` int(255) NOT NULL,
  `Qid51` text NOT NULL,
  `Q52` int(255) NOT NULL,
  `Qid52` text NOT NULL,
  `Q53` int(255) NOT NULL,
  `Qid53` text NOT NULL,
  `Q54` int(255) NOT NULL,
  `Qid54` text NOT NULL,
  `Q55` int(255) NOT NULL,
  `Qid55` text NOT NULL,
  `Q56` int(255) NOT NULL,
  `Qid56` text NOT NULL,
  `Q57` int(255) NOT NULL,
  `Qid57` text NOT NULL,
  `Q58` int(255) NOT NULL,
  `Qid58` text NOT NULL,
  `Q59` int(255) NOT NULL,
  `Qid59` text NOT NULL,
  `Q60` int(255) NOT NULL,
  `Qid60` text NOT NULL,
  `Q61` int(255) NOT NULL,
  `Qid61` text NOT NULL,
  `Q62` int(255) NOT NULL,
  `Qid62` text NOT NULL,
  `Q63` int(255) NOT NULL,
  `Qid63` text NOT NULL,
  `Q64` int(255) NOT NULL,
  `Qid64` text NOT NULL,
  `Q65` int(255) NOT NULL,
  `Qid65` text NOT NULL,
  `Q66` int(255) NOT NULL,
  `Qid66` text NOT NULL,
  `Q67` int(255) NOT NULL,
  `Qid67` text NOT NULL,
  `Q68` int(255) NOT NULL,
  `Qid68` text NOT NULL,
  `Q69` int(255) NOT NULL,
  `Qid69` text NOT NULL,
  `Q70` int(255) NOT NULL,
  `Qid70` text NOT NULL,
  `Q71` int(255) NOT NULL,
  `Qid71` text NOT NULL,
  `Q72` int(255) NOT NULL,
  `Qid72` text NOT NULL,
  `Q73` int(255) NOT NULL,
  `Qid73` text NOT NULL,
  `Q74` int(255) NOT NULL,
  `Qid74` text NOT NULL,
  `Q75` int(255) NOT NULL,
  `Qid75` text NOT NULL,
  `Q76` int(255) NOT NULL,
  `Qid76` text NOT NULL,
  `Q77` int(255) NOT NULL,
  `Qid77` text NOT NULL,
  `Q78` int(255) NOT NULL,
  `Qid78` text NOT NULL,
  `Q79` int(255) NOT NULL,
  `Qid79` text NOT NULL,
  `Q80` int(255) NOT NULL,
  `Qid80` text NOT NULL,
  `Q81` int(255) NOT NULL,
  `Qid81` text NOT NULL,
  `Q82` int(255) NOT NULL,
  `Qid82` text NOT NULL,
  `Q83` int(255) NOT NULL,
  `Qid83` text NOT NULL,
  `Q84` int(255) NOT NULL,
  `Qid84` text NOT NULL,
  `Q85` int(255) NOT NULL,
  `Qid85` text NOT NULL,
  `Q86` int(255) NOT NULL,
  `Qid86` text NOT NULL,
  `Q87` int(255) NOT NULL,
  `Qid87` text NOT NULL,
  `Q88` int(255) NOT NULL,
  `Qid88` text NOT NULL,
  `Q89` int(255) NOT NULL,
  `Qid89` text NOT NULL,
  `Q90` int(255) NOT NULL,
  `Qid90` text NOT NULL,
  `Q91` int(255) NOT NULL,
  `Qid91` text NOT NULL,
  `Q92` int(255) NOT NULL,
  `Qid92` text NOT NULL,
  `Q93` int(255) NOT NULL,
  `Qid93` text NOT NULL,
  `Q94` int(255) NOT NULL,
  `Qid94` text NOT NULL,
  `Q95` int(255) NOT NULL,
  `Qid95` text NOT NULL,
  `Q96` int(255) NOT NULL,
  `Qid96` text NOT NULL,
  `Q97` int(255) NOT NULL,
  `Qid97` text NOT NULL,
  `Q98` int(255) NOT NULL,
  `Qid98` text NOT NULL,
  `Q99` int(255) NOT NULL,
  `Qid99` text NOT NULL,
  `Q100` int(255) NOT NULL,
  `Qid100` text NOT NULL,
  PRIMARY KEY (`A_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_ft_answer_type_a = $conn->query("CREATE TABLE IF NOT EXISTS `ft_answer_type_a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_ft_answer_type_b = $conn->query("CREATE TABLE IF NOT EXISTS `ft_answer_type_b` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_ft_answer_type_c = $conn->query("CREATE TABLE IF NOT EXISTS `ft_answer_type_c` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_ft_exam_type_a = $conn->query("CREATE TABLE IF NOT EXISTS `ft_exam_type_a` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_ft_exam_type_b = $conn->query("CREATE TABLE IF NOT EXISTS `ft_exam_type_b` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_ft_exam_type_c = $conn->query("CREATE TABLE IF NOT EXISTS `ft_exam_type_c` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_instruction_tbl = $conn->query("CREATE TABLE IF NOT EXISTS `instruction_tbl` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `instruction1` mediumtext NOT NULL,
  `instruction2` mediumtext NOT NULL,
  `instruction3` mediumtext NOT NULL,
  `instruction4` mediumtext NOT NULL,
  `instruction5` mediumtext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_school_details = $conn->query("CREATE TABLE IF NOT EXISTS `school_details` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sch_phone` varchar(100) NOT NULL,
  `sch_phone2` varchar(100) NOT NULL,
  `sch_email` varchar(100) NOT NULL,
  `sch_facebook` varchar(1000) NOT NULL,
  `sch_whatsapp` varchar(1000) NOT NULL,
  `sch_twitter` varchar(1000) NOT NULL,
  `sch_instagram` varchar(1000) NOT NULL,
  `sch_name` varchar(255) NOT NULL,
  `sch_name2` varchar(100) NOT NULL,
  `sch_address` varchar(255) NOT NULL,
  `sch_logo` varchar(255) NOT NULL,
  `header_col` varchar(255) NOT NULL,
  `header_txt_col` varchar(255) NOT NULL,
  `term` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

if ($cr_school_details) {
  $checkSch = $conn->query("SELECT * FROM $school_details_tbl WHERE header_col != ''");
  if ($checkSch->num_rows == 0) {
    $conn->query("INSERT INTO $school_details_tbl (sch_phone, sch_phone2, sch_email, sch_facebook, sch_whatsapp, sch_twitter, sch_instagram, sch_name, sch_name2, sch_address, sch_logo, header_col, header_txt_col) 
    VALUES('07069056472', '07034876144', 'ekreat2016@gmail.com', 'https://facebook.com', 'https://wa.me/+2348061284140', 'https://twitter.com', 'https://instagram.com', 'EKREAT SCHOOLS', 'Success gateway', '16, Orire lane Adebayo, Ado-Ekiti. Ekiti State', 'eksu logo.png', '#bef9e7', '#0d0c0c')");
  }
}

$cr_school_term = $conn->query("CREATE TABLE IF NOT EXISTS `school_term` (
  `T_id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `sch_term` varchar(100) NOT NULL,
  `code` varchar(100) NOT NULL,
  PRIMARY KEY (`T_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

if ($cr_school_term) {
  $checkPer = $conn->query("SELECT * FROM $school_period_tbl WHERE sch_term != ''");
  if ($checkPer->num_rows == 0) {
    $conn->query("INSERT INTO $school_period_tbl (session, sch_term, code) VALUES('2021/2022', 'First Term', '1')");
  }
}
$cr_sch_session = $conn->query("CREATE TABLE IF NOT EXISTS `sch_session` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");


if ($cr_sch_session) {
  $checkSess = $conn->query("SELECT * FROM $school_period_tbl WHERE session != ''");
  if ($checkSess->num_rows == 0) {
    $conn->query("INSERT INTO $sch_session_tbl (session) VALUES('2021/2022')");
  }
}

$cr_student = $conn->query("CREATE TABLE IF NOT EXISTS `student` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reg_date` varchar(100) NOT NULL,
  `session` varchar(255) NOT NULL,
  `fullname` varchar(255) NOT NULL,
  `class` varchar(100) NOT NULL,
  `adm_no` varchar(255) NOT NULL,
  `gender` varchar(50) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `p_image` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `reset` int(11) NOT NULL,
  `keyp` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_st_answer_sheet = $conn->query("CREATE TABLE IF NOT EXISTS `st_answer_sheet` (
  `A_id` int(11) NOT NULL AUTO_INCREMENT,
  `subject` mediumtext NOT NULL,
  `paper_type` text NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `teacher` varchar(255) NOT NULL,
  `teacher_token` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `duration` int(11) NOT NULL,
  `session` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `fullname` varchar(255) NOT NULL,
  `adm_no` varchar(255) NOT NULL,
  `ft_score` int(11) NOT NULL,
  `CA1` int(11) NOT NULL,
  `CA2` int(11) NOT NULL,
  `CA3` int(11) NOT NULL,
  `test` int(11) NOT NULL,
  `obj_score` int(11) NOT NULL,
  `essay_score` int(11) NOT NULL,
  `exam_total` int(11) NOT NULL,
  `total` int(11) NOT NULL,
  `position` varchar(255) NOT NULL,
  `grade` text NOT NULL,
  `remark` varchar(255) NOT NULL,
  `color` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `Q1` int(255) NOT NULL,
  `Qid1` text NOT NULL,
  `Q2` int(255) NOT NULL,
  `Qid2` text NOT NULL,
  `Q3` int(255) NOT NULL,
  `Qid3` text NOT NULL,
  `Q4` int(255) NOT NULL,
  `Qid4` text NOT NULL,
  `Q5` int(255) NOT NULL,
  `Qid5` text NOT NULL,
  `Q6` int(255) NOT NULL,
  `Qid6` text NOT NULL,
  `Q7` int(255) NOT NULL,
  `Qid7` text NOT NULL,
  `Q8` int(255) NOT NULL,
  `Qid8` text NOT NULL,
  `Q9` int(255) NOT NULL,
  `Qid9` text NOT NULL,
  `Q10` int(255) NOT NULL,
  `Qid10` text NOT NULL,
  `Q11` int(255) NOT NULL,
  `Qid11` text NOT NULL,
  `Q12` int(255) NOT NULL,
  `Qid12` text NOT NULL,
  `Q13` int(255) NOT NULL,
  `Qid13` text NOT NULL,
  `Q14` int(255) NOT NULL,
  `Qid14` text NOT NULL,
  `Q15` int(255) NOT NULL,
  `Qid15` text NOT NULL,
  `Q16` int(255) NOT NULL,
  `Qid16` text NOT NULL,
  `Q17` int(255) NOT NULL,
  `Qid17` text NOT NULL,
  `Q18` int(255) NOT NULL,
  `Qid18` text NOT NULL,
  `Q19` int(255) NOT NULL,
  `Qid19` text NOT NULL,
  `Q20` int(255) NOT NULL,
  `Qid20` text NOT NULL,
  `Q21` int(255) NOT NULL,
  `Qid21` text NOT NULL,
  `Q22` int(255) NOT NULL,
  `Qid22` text NOT NULL,
  `Q23` int(255) NOT NULL,
  `Qid23` text NOT NULL,
  `Q24` int(255) NOT NULL,
  `Qid24` text NOT NULL,
  `Q25` int(255) NOT NULL,
  `Qid25` text NOT NULL,
  `Q26` int(255) NOT NULL,
  `Qid26` text NOT NULL,
  `Q27` int(255) NOT NULL,
  `Qid27` text NOT NULL,
  `Q28` int(255) NOT NULL,
  `Qid28` text NOT NULL,
  `Q29` int(255) NOT NULL,
  `Qid29` text NOT NULL,
  `Q30` int(255) NOT NULL,
  `Qid30` text NOT NULL,
  `Q31` int(255) NOT NULL,
  `Qid31` text NOT NULL,
  `Q32` int(255) NOT NULL,
  `Qid32` text NOT NULL,
  `Q33` int(255) NOT NULL,
  `Qid33` text NOT NULL,
  `Q34` int(255) NOT NULL,
  `Qid34` text NOT NULL,
  `Q35` int(255) NOT NULL,
  `Qid35` text NOT NULL,
  `Q36` int(255) NOT NULL,
  `Qid36` text NOT NULL,
  `Q37` int(255) NOT NULL,
  `Qid37` text NOT NULL,
  `Q38` int(255) NOT NULL,
  `Qid38` text NOT NULL,
  `Q39` int(255) NOT NULL,
  `Qid39` text NOT NULL,
  `Q40` int(255) NOT NULL,
  `Qid40` text NOT NULL,
  `Q41` int(255) NOT NULL,
  `Qid41` text NOT NULL,
  `Q42` int(255) NOT NULL,
  `Qid42` text NOT NULL,
  `Q43` int(255) NOT NULL,
  `Qid43` text NOT NULL,
  `Q44` int(255) NOT NULL,
  `Qid44` text NOT NULL,
  `Q45` int(255) NOT NULL,
  `Qid45` text NOT NULL,
  `Q46` int(255) NOT NULL,
  `Qid46` text NOT NULL,
  `Q47` int(255) NOT NULL,
  `Qid47` text NOT NULL,
  `Q48` int(255) NOT NULL,
  `Qid48` text NOT NULL,
  `Q49` int(255) NOT NULL,
  `Qid49` text NOT NULL,
  `Q50` int(255) NOT NULL,
  `Qid50` text NOT NULL,
  `Q51` int(255) NOT NULL,
  `Qid51` text NOT NULL,
  `Q52` int(255) NOT NULL,
  `Qid52` text NOT NULL,
  `Q53` int(255) NOT NULL,
  `Qid53` text NOT NULL,
  `Q54` int(255) NOT NULL,
  `Qid54` text NOT NULL,
  `Q55` int(255) NOT NULL,
  `Qid55` text NOT NULL,
  `Q56` int(255) NOT NULL,
  `Qid56` text NOT NULL,
  `Q57` int(255) NOT NULL,
  `Qid57` text NOT NULL,
  `Q58` int(255) NOT NULL,
  `Qid58` text NOT NULL,
  `Q59` int(255) NOT NULL,
  `Qid59` text NOT NULL,
  `Q60` int(255) NOT NULL,
  `Qid60` text NOT NULL,
  `Q61` int(255) NOT NULL,
  `Qid61` text NOT NULL,
  `Q62` int(255) NOT NULL,
  `Qid62` text NOT NULL,
  `Q63` int(255) NOT NULL,
  `Qid63` text NOT NULL,
  `Q64` int(255) NOT NULL,
  `Qid64` text NOT NULL,
  `Q65` int(255) NOT NULL,
  `Qid65` text NOT NULL,
  `Q66` int(255) NOT NULL,
  `Qid66` text NOT NULL,
  `Q67` int(255) NOT NULL,
  `Qid67` text NOT NULL,
  `Q68` int(255) NOT NULL,
  `Qid68` text NOT NULL,
  `Q69` int(255) NOT NULL,
  `Qid69` text NOT NULL,
  `Q70` int(255) NOT NULL,
  `Qid70` text NOT NULL,
  `Q71` int(255) NOT NULL,
  `Qid71` text NOT NULL,
  `Q72` int(255) NOT NULL,
  `Qid72` text NOT NULL,
  `Q73` int(255) NOT NULL,
  `Qid73` text NOT NULL,
  `Q74` int(255) NOT NULL,
  `Qid74` text NOT NULL,
  `Q75` int(255) NOT NULL,
  `Qid75` text NOT NULL,
  `Q76` int(255) NOT NULL,
  `Qid76` text NOT NULL,
  `Q77` int(255) NOT NULL,
  `Qid77` text NOT NULL,
  `Q78` int(255) NOT NULL,
  `Qid78` text NOT NULL,
  `Q79` int(255) NOT NULL,
  `Qid79` text NOT NULL,
  `Q80` int(255) NOT NULL,
  `Qid80` text NOT NULL,
  `Q81` int(255) NOT NULL,
  `Qid81` text NOT NULL,
  `Q82` int(255) NOT NULL,
  `Qid82` text NOT NULL,
  `Q83` int(255) NOT NULL,
  `Qid83` text NOT NULL,
  `Q84` int(255) NOT NULL,
  `Qid84` text NOT NULL,
  `Q85` int(255) NOT NULL,
  `Qid85` text NOT NULL,
  `Q86` int(255) NOT NULL,
  `Qid86` text NOT NULL,
  `Q87` int(255) NOT NULL,
  `Qid87` text NOT NULL,
  `Q88` int(255) NOT NULL,
  `Qid88` text NOT NULL,
  `Q89` int(255) NOT NULL,
  `Qid89` text NOT NULL,
  `Q90` int(255) NOT NULL,
  `Qid90` text NOT NULL,
  `Q91` int(255) NOT NULL,
  `Qid91` text NOT NULL,
  `Q92` int(255) NOT NULL,
  `Qid92` text NOT NULL,
  `Q93` int(255) NOT NULL,
  `Qid93` text NOT NULL,
  `Q94` int(255) NOT NULL,
  `Qid94` text NOT NULL,
  `Q95` int(255) NOT NULL,
  `Qid95` text NOT NULL,
  `Q96` int(255) NOT NULL,
  `Qid96` text NOT NULL,
  `Q97` int(255) NOT NULL,
  `Qid97` text NOT NULL,
  `Q98` int(255) NOT NULL,
  `Qid98` text NOT NULL,
  `Q99` int(255) NOT NULL,
  `Qid99` text NOT NULL,
  `Q100` int(255) NOT NULL,
  `Qid100` text NOT NULL,
  PRIMARY KEY (`A_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_st_answer_type_a = $conn->query("CREATE TABLE IF NOT EXISTS `st_answer_type_a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_st_answer_type_b = $conn->query("CREATE TABLE IF NOT EXISTS `st_answer_type_b` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_st_answer_type_c = $conn->query("CREATE TABLE IF NOT EXISTS `st_answer_type_c` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_st_exam_type_a = $conn->query("CREATE TABLE IF NOT EXISTS `st_exam_type_a` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_st_exam_type_b = $conn->query("CREATE TABLE IF NOT EXISTS `st_exam_type_b` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_st_exam_type_c = $conn->query("CREATE TABLE IF NOT EXISTS `st_exam_type_c` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_subject_tbl = $conn->query("CREATE TABLE IF NOT EXISTS `subject_tbl` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `teacher` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `no_of_quest` int(11) NOT NULL,
  `term` int(11) NOT NULL,
  `course_unit` int(11) NOT NULL,
  `class` varchar(255) NOT NULL,
  `duration` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_subject_time_table = $conn->query("CREATE TABLE IF NOT EXISTS `subject_time_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `exam_order` varchar(255) NOT NULL,
  `day` varchar(255) NOT NULL,
  `gen_code` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_subject_time_table_2 = $conn->query("CREATE TABLE IF NOT EXISTS `subject_time_table_2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `exam_order` varchar(255) NOT NULL,
  `day` varchar(255) NOT NULL,
  `gen_code` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_subject_time_table_3 = $conn->query("CREATE TABLE IF NOT EXISTS `subject_time_table_3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `exam_order` varchar(255) NOT NULL,
  `day` varchar(255) NOT NULL,
  `gen_code` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_teacher_reg_key = $conn->query("CREATE TABLE IF NOT EXISTS `teacher_reg_key` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `surname` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `position` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_tt_answer_sheet = $conn->query("CREATE TABLE IF NOT EXISTS `tt_answer_sheet` (
  `A_id` int(11) NOT NULL AUTO_INCREMENT,
  `subject` mediumtext NOT NULL,
  `paper_type` text NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `teacher` varchar(255) NOT NULL,
  `teacher_token` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `duration` int(11) NOT NULL,
  `session` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `fullname` varchar(255) NOT NULL,
  `adm_no` varchar(255) NOT NULL,
  `ft_score` int(11) NOT NULL,
  `st_score` int(11) NOT NULL,
  `CA1` int(11) NOT NULL,
  `CA2` int(11) NOT NULL,
  `CA3` int(11) NOT NULL,
  `test` int(11) NOT NULL,
  `obj_score` int(11) NOT NULL,
  `essay_score` int(11) NOT NULL,
  `exam_total` int(11) NOT NULL,
  `total` int(11) NOT NULL,
  `position` varchar(255) NOT NULL,
  `grade` text NOT NULL,
  `remark` varchar(255) NOT NULL,
  `color` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `Q1` int(255) NOT NULL,
  `Qid1` text NOT NULL,
  `Q2` int(255) NOT NULL,
  `Qid2` text NOT NULL,
  `Q3` int(255) NOT NULL,
  `Qid3` text NOT NULL,
  `Q4` int(255) NOT NULL,
  `Qid4` text NOT NULL,
  `Q5` int(255) NOT NULL,
  `Qid5` text NOT NULL,
  `Q6` int(255) NOT NULL,
  `Qid6` text NOT NULL,
  `Q7` int(255) NOT NULL,
  `Qid7` text NOT NULL,
  `Q8` int(255) NOT NULL,
  `Qid8` text NOT NULL,
  `Q9` int(255) NOT NULL,
  `Qid9` text NOT NULL,
  `Q10` int(255) NOT NULL,
  `Qid10` text NOT NULL,
  `Q11` int(255) NOT NULL,
  `Qid11` text NOT NULL,
  `Q12` int(255) NOT NULL,
  `Qid12` text NOT NULL,
  `Q13` int(255) NOT NULL,
  `Qid13` text NOT NULL,
  `Q14` int(255) NOT NULL,
  `Qid14` text NOT NULL,
  `Q15` int(255) NOT NULL,
  `Qid15` text NOT NULL,
  `Q16` int(255) NOT NULL,
  `Qid16` text NOT NULL,
  `Q17` int(255) NOT NULL,
  `Qid17` text NOT NULL,
  `Q18` int(255) NOT NULL,
  `Qid18` text NOT NULL,
  `Q19` int(255) NOT NULL,
  `Qid19` text NOT NULL,
  `Q20` int(255) NOT NULL,
  `Qid20` text NOT NULL,
  `Q21` int(255) NOT NULL,
  `Qid21` text NOT NULL,
  `Q22` int(255) NOT NULL,
  `Qid22` text NOT NULL,
  `Q23` int(255) NOT NULL,
  `Qid23` text NOT NULL,
  `Q24` int(255) NOT NULL,
  `Qid24` text NOT NULL,
  `Q25` int(255) NOT NULL,
  `Qid25` text NOT NULL,
  `Q26` int(255) NOT NULL,
  `Qid26` text NOT NULL,
  `Q27` int(255) NOT NULL,
  `Qid27` text NOT NULL,
  `Q28` int(255) NOT NULL,
  `Qid28` text NOT NULL,
  `Q29` int(255) NOT NULL,
  `Qid29` text NOT NULL,
  `Q30` int(255) NOT NULL,
  `Qid30` text NOT NULL,
  `Q31` int(255) NOT NULL,
  `Qid31` text NOT NULL,
  `Q32` int(255) NOT NULL,
  `Qid32` text NOT NULL,
  `Q33` int(255) NOT NULL,
  `Qid33` text NOT NULL,
  `Q34` int(255) NOT NULL,
  `Qid34` text NOT NULL,
  `Q35` int(255) NOT NULL,
  `Qid35` text NOT NULL,
  `Q36` int(255) NOT NULL,
  `Qid36` text NOT NULL,
  `Q37` int(255) NOT NULL,
  `Qid37` text NOT NULL,
  `Q38` int(255) NOT NULL,
  `Qid38` text NOT NULL,
  `Q39` int(255) NOT NULL,
  `Qid39` text NOT NULL,
  `Q40` int(255) NOT NULL,
  `Qid40` text NOT NULL,
  `Q41` int(255) NOT NULL,
  `Qid41` text NOT NULL,
  `Q42` int(255) NOT NULL,
  `Qid42` text NOT NULL,
  `Q43` int(255) NOT NULL,
  `Qid43` text NOT NULL,
  `Q44` int(255) NOT NULL,
  `Qid44` text NOT NULL,
  `Q45` int(255) NOT NULL,
  `Qid45` text NOT NULL,
  `Q46` int(255) NOT NULL,
  `Qid46` text NOT NULL,
  `Q47` int(255) NOT NULL,
  `Qid47` text NOT NULL,
  `Q48` int(255) NOT NULL,
  `Qid48` text NOT NULL,
  `Q49` int(255) NOT NULL,
  `Qid49` text NOT NULL,
  `Q50` int(255) NOT NULL,
  `Qid50` text NOT NULL,
  `Q51` int(255) NOT NULL,
  `Qid51` text NOT NULL,
  `Q52` int(255) NOT NULL,
  `Qid52` text NOT NULL,
  `Q53` int(255) NOT NULL,
  `Qid53` text NOT NULL,
  `Q54` int(255) NOT NULL,
  `Qid54` text NOT NULL,
  `Q55` int(255) NOT NULL,
  `Qid55` text NOT NULL,
  `Q56` int(255) NOT NULL,
  `Qid56` text NOT NULL,
  `Q57` int(255) NOT NULL,
  `Qid57` text NOT NULL,
  `Q58` int(255) NOT NULL,
  `Qid58` text NOT NULL,
  `Q59` int(255) NOT NULL,
  `Qid59` text NOT NULL,
  `Q60` int(255) NOT NULL,
  `Qid60` text NOT NULL,
  `Q61` int(255) NOT NULL,
  `Qid61` text NOT NULL,
  `Q62` int(255) NOT NULL,
  `Qid62` text NOT NULL,
  `Q63` int(255) NOT NULL,
  `Qid63` text NOT NULL,
  `Q64` int(255) NOT NULL,
  `Qid64` text NOT NULL,
  `Q65` int(255) NOT NULL,
  `Qid65` text NOT NULL,
  `Q66` int(255) NOT NULL,
  `Qid66` text NOT NULL,
  `Q67` int(255) NOT NULL,
  `Qid67` text NOT NULL,
  `Q68` int(255) NOT NULL,
  `Qid68` text NOT NULL,
  `Q69` int(255) NOT NULL,
  `Qid69` text NOT NULL,
  `Q70` int(255) NOT NULL,
  `Qid70` text NOT NULL,
  `Q71` int(255) NOT NULL,
  `Qid71` text NOT NULL,
  `Q72` int(255) NOT NULL,
  `Qid72` text NOT NULL,
  `Q73` int(255) NOT NULL,
  `Qid73` text NOT NULL,
  `Q74` int(255) NOT NULL,
  `Qid74` text NOT NULL,
  `Q75` int(255) NOT NULL,
  `Qid75` text NOT NULL,
  `Q76` int(255) NOT NULL,
  `Qid76` text NOT NULL,
  `Q77` int(255) NOT NULL,
  `Qid77` text NOT NULL,
  `Q78` int(255) NOT NULL,
  `Qid78` text NOT NULL,
  `Q79` int(255) NOT NULL,
  `Qid79` text NOT NULL,
  `Q80` int(255) NOT NULL,
  `Qid80` text NOT NULL,
  `Q81` int(255) NOT NULL,
  `Qid81` text NOT NULL,
  `Q82` int(255) NOT NULL,
  `Qid82` text NOT NULL,
  `Q83` int(255) NOT NULL,
  `Qid83` text NOT NULL,
  `Q84` int(255) NOT NULL,
  `Qid84` text NOT NULL,
  `Q85` int(255) NOT NULL,
  `Qid85` text NOT NULL,
  `Q86` int(255) NOT NULL,
  `Qid86` text NOT NULL,
  `Q87` int(255) NOT NULL,
  `Qid87` text NOT NULL,
  `Q88` int(255) NOT NULL,
  `Qid88` text NOT NULL,
  `Q89` int(255) NOT NULL,
  `Qid89` text NOT NULL,
  `Q90` int(255) NOT NULL,
  `Qid90` text NOT NULL,
  `Q91` int(255) NOT NULL,
  `Qid91` text NOT NULL,
  `Q92` int(255) NOT NULL,
  `Qid92` text NOT NULL,
  `Q93` int(255) NOT NULL,
  `Qid93` text NOT NULL,
  `Q94` int(255) NOT NULL,
  `Qid94` text NOT NULL,
  `Q95` int(255) NOT NULL,
  `Qid95` text NOT NULL,
  `Q96` int(255) NOT NULL,
  `Qid96` text NOT NULL,
  `Q97` int(255) NOT NULL,
  `Qid97` text NOT NULL,
  `Q98` int(255) NOT NULL,
  `Qid98` text NOT NULL,
  `Q99` int(255) NOT NULL,
  `Qid99` text NOT NULL,
  `Q100` int(255) NOT NULL,
  `Qid100` text NOT NULL,
  PRIMARY KEY (`A_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_tt_answer_type_a = $conn->query("CREATE TABLE IF NOT EXISTS `tt_answer_type_a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_tt_answer_type_b = $conn->query("CREATE TABLE IF NOT EXISTS `tt_answer_type_b` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_tt_answer_type_c = $conn->query("CREATE TABLE IF NOT EXISTS `tt_answer_type_c` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session` varchar(255) NOT NULL,
  `user_token` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(11) NOT NULL,
  `is_correct` int(11) NOT NULL,
  `alpha_opt` varchar(255) NOT NULL,
  `text` varchar(1000) NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_tt_exam_type_a = $conn->query("CREATE TABLE IF NOT EXISTS `tt_exam_type_a` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_tt_exam_type_b = $conn->query("CREATE TABLE IF NOT EXISTS `tt_exam_type_b` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");

$cr_tt_exam_type_c = $conn->query("CREATE TABLE IF NOT EXISTS `tt_exam_type_c` (
  `Q_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_token` varchar(255) NOT NULL,
  `session` varchar(255) NOT NULL,
  `subject` varchar(1000) NOT NULL,
  `course_code` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `question_number` int(255) NOT NULL,
  `text` text NOT NULL,
  `quest_code` varchar(255) NOT NULL,
  `quest_img` varchar(255) NOT NULL,
  PRIMARY KEY (`Q_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
");
