<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit754e4ea97120c0b7c1d355dded21d995
{
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
